name: CountMe
on:
  schedule: [{cron: "0 1 * * *"}]
  workflow_dispatch:
jobs:
  countme-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download File
        run: |
          curl https://raw.githubusercontent.com/ublue-os/countme/refs/heads/main/growth_bazzite.svg --output ./countme.svg
        working-directory: ${{ github.workspace }}

      - name: Write countme.svg to Repostiory
        uses: test-room-7/action-update-file@v2
        with:
            file-path: countme.svg
            commit-msg: CountMe Update
            github-token: ${{ secrets.GITHUB_TOKEN }}
